// Rebuild with: node scripts/generate_line_spectra.mjs
// One deterministic 131072-bit stream for every line code. Rectangular half-bit
// levels are sampled 8 times per bit; the existing Welch implementation uses
// 32768-sample Hann windows with 50% overlap (63 windows per spectrum).
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {lineCodes} from '../course/interactives/companding-line-model.js';
import {averagedPowerSpectrum, PRACTICE_FFT_SIZE} from '../course/interactives/impulse-ask-model.js';

const BIT_COUNT = 131072;
const SAMPLES_PER_BIT = 8;
const MAX_FREQUENCY = 2.5;
const KEYS = ['nrz', 'rz', 'amiNrz', 'amiRz', 'manchester', 'hdb'];
let seed = 0x71ac37;
let bits = '';
for (let i = 0; i < BIT_COUNT; i++) {
  seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
  bits += seed >>> 31;
}
const codes = lineCodes(bits, BIT_COUNT);
const spectra = {};
for (const key of KEYS) {
  const levels = codes[key];
  const signal = new Float64Array(BIT_COUNT * SAMPLES_PER_BIT);
  let sum = 0;
  for (let bit = 0; bit < BIT_COUNT; bit++) {
    const pair = key === 'hdb' ? [levels[bit].level, levels[bit].level] : levels[bit];
    for (let sample = 0; sample < SAMPLES_PER_BIT; sample++) {
      const value = pair[sample < SAMPLES_PER_BIT / 2 ? 0 : 1];
      signal[bit * SAMPLES_PER_BIT + sample] = value;
      sum += value;
    }
  }
  const mean = sum / signal.length;
  for (let i = 0; i < signal.length; i++) signal[i] -= mean;
  const {power, windows} = averagedPowerSpectrum(signal, PRACTICE_FFT_SIZE);
  // f/Rb = FFT bin / 4096: each window spans 4096 bits. Average nearby
  // frequency bins for a legible power envelope; isolate deterministic clock
  // lines so they do not distort the continuous part of the spectrum.
  const binsPerBitRate = PRACTICE_FFT_SIZE / SAMPLES_PER_BIT;
  const points = [];
  const pointCount = 500;
  for (let point = 0; point <= pointCount; point++) {
    const from = Math.round(point * MAX_FREQUENCY * binsPerBitRate / pointCount);
    const to = Math.round((point + 1) * MAX_FREQUENCY * binsPerBitRate / pointCount);
    let total = 0;
    let included = 0;
    for (let bin = Math.max(1, from); bin < to; bin++) {
      if (key === 'rz' && Math.abs(bin - binsPerBitRate) <= 4) continue;
      total += power[bin];
      included++;
    }
    points.push(included ? total / included : (points.at(-1) ?? 0));
  }
  // The long FFT windows resolve fine detail; a short triangular display
  // average removes residual Monte Carlo noise without hiding the main lobes.
  const smoothed = points.map((_, index) => {
    let weighted = 0, weightSum = 0;
    for (let offset = -5; offset <= 5; offset++) {
      const neighbor = index + offset;
      if (neighbor < 0 || neighbor >= points.length) continue;
      const weight = 6 - Math.abs(offset);
      weighted += weight * points[neighbor];
      weightSum += weight;
    }
    return weighted / weightSum;
  });
  const reference = Math.max(...smoothed);
  spectra[key] = {
    mean: Number(mean.toFixed(5)),
    referencePower: Number(reference.toPrecision(8)),
    relativePower: smoothed.map(value => Number((value / reference).toFixed(4))),
  };
  if (windows !== 63) throw new Error(`Expected 63 Welch windows, got ${windows}`);
}
const output = fileURLToPath(new URL('../course/interactives/line-spectrum-data.js', import.meta.url));
writeFileSync(output, `// Generated by scripts/generate_line_spectra.mjs; do not edit by hand.\nexport const LINE_SPECTRA = ${JSON.stringify({bitCount:BIT_COUNT, samplesPerBit:SAMPLES_PER_BIT, fftSize:PRACTICE_FFT_SIZE, windows:63, maxFrequency:MAX_FREQUENCY, spectra})};\n`);
console.log(`Wrote six line-code spectra from ${BIT_COUNT} bits, 63 overlapping FFT windows each.`);
