// Rebuild with: node scripts/generate_line_spectra.mjs
// One deterministic 131072-bit stream for every line code. Rectangular half-bit
// levels are sampled 8 times per bit; the existing Welch implementation uses
// 32768-sample Hann windows with 50% overlap (63 windows per spectrum).
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {lineCodes} from '../course/interactives/companding-line-model.js';
import {averagedPowerSpectrum, PRACTICE_FFT_SIZE} from '../course/interactives/impulse-ask-model.js';

const BIT_COUNT = 131072;
const SAMPLES_PER_BIT = 8;
const KEYS = ['nrz', 'rz', 'amiNrz', 'amiRz', 'manchester', 'hdb'];
let seed = 0x71ac37;
let bits = '';
for (let i = 0; i < BIT_COUNT; i++) {
  seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
  bits += seed >>> 31;
}
const codes = lineCodes(bits, BIT_COUNT);
const spectra = {};
for (const key of KEYS) {
  const levels = codes[key];
  const signal = new Float64Array(BIT_COUNT * SAMPLES_PER_BIT);
  let sum = 0;
  for (let bit = 0; bit < BIT_COUNT; bit++) {
    const pair = key === 'hdb' ? [levels[bit].level, levels[bit].level] : levels[bit];
    for (let sample = 0; sample < SAMPLES_PER_BIT; sample++) {
      const value = pair[sample < SAMPLES_PER_BIT / 2 ? 0 : 1];
      signal[bit * SAMPLES_PER_BIT + sample] = value;
      sum += value;
    }
  }
  const mean = sum / signal.length;
  for (let i = 0; i < signal.length; i++) signal[i] -= mean;
  const {power, windows} = averagedPowerSpectrum(signal, PRACTICE_FFT_SIZE);
  // f/Rb = FFT bin / 4096: each window spans 4096 bits.
  const binsPerBitRate = PRACTICE_FFT_SIZE / SAMPLES_PER_BIT;
  const points = [];
  for (let point = 0; point <= 1024; point++) {
    const from = Math.round(point * 3.5 * binsPerBitRate / 1024);
    const to = Math.round((point + 1) * 3.5 * binsPerBitRate / 1024);
    let total = 0;
    for (let bin = Math.max(1, from); bin < to; bin++) total += power[bin];
    points.push(total / Math.max(1, to - Math.max(1, from)));
  }
  // Use the upper envelope of the diffuse part as the reference, so the
  // narrow RZ clock line remains visible above 0 dB rather than flattening it.
  const sorted = points.slice(15).sort((a, b) => a - b);
  const reference = sorted[Math.floor(0.95 * (sorted.length - 1))];
  spectra[key] = {
    mean: Number(mean.toFixed(5)),
    db: points.map(value => Number(Math.max(-50, Math.min(25, 10 * Math.log10(Math.max(value / reference, 1e-10)))).toFixed(1))),
  };
  if (windows !== 63) throw new Error(`Expected 63 Welch windows, got ${windows}`);
}
const output = fileURLToPath(new URL('../course/interactives/line-spectrum-data.js', import.meta.url));
writeFileSync(output, `// Generated by scripts/generate_line_spectra.mjs; do not edit by hand.\nexport const LINE_SPECTRA = ${JSON.stringify({bitCount:BIT_COUNT, samplesPerBit:SAMPLES_PER_BIT, fftSize:PRACTICE_FFT_SIZE, windows:63, maxFrequency:3.5, spectra})};\n`);
console.log(`Wrote six line-code spectra from ${BIT_COUNT} bits, 63 overlapping FFT windows each.`);
