// Rebuild with: node scripts/generate_line_spectra.mjs
// Fourier series of steady, periodically repeated bit patterns. Each bit has
// two constant half-bit levels; exact integration includes their sinc shape.
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {lineCodes} from '../course/interactives/companding-line-model.js';

const MAX_FREQUENCY = 2.5; // f/Rb
const COMPARISONS = [
  {keys: ['nrz', 'rz'], pattern: '10'},
  {keys: ['amiNrz', 'amiRz'], pattern: '110'},
  {keys: ['hdb', 'manchester'], pattern: '10000'},
];

function halfBitLevels(cells, key) {
  return cells.flatMap(cell => key === 'hdb' ? [cell.level, cell.level] : cell);
}

function steadyPeriod(levels, patternBits) {
  const halfBitsPerPattern = 2 * patternBits;
  for (let repeats = 1; repeats <= 16; repeats++) {
    const length = repeats * halfBitsPerPattern;
    if (levels.length < 3 * length) continue;
    const end = levels.length;
    if (levels.slice(end - length).every((value, index) =>
      value === levels[end - 2 * length + index] &&
      value === levels[end - 3 * length + index])) {
      return levels.slice(end - length);
    }
  }
  throw new Error('No steady periodic line-code waveform found');
}

function harmonics(period) {
  const halfBitCount = period.length;
  const periodBits = halfBitCount / 2;
  const lines = [];
  for (let order = 0; order <= Math.floor(MAX_FREQUENCY * periodBits); order++) {
    let real = 0, imaginary = 0;
    for (let cell = 0; cell < halfBitCount; cell++) {
      const phase = 2 * Math.PI * order * (cell + .5) / halfBitCount;
      real += period[cell] * Math.cos(phase);
      imaginary -= period[cell] * Math.sin(phase);
    }
    const sinc = order === 0 ? 1 : Math.sin(Math.PI * order / halfBitCount) / (Math.PI * order / halfBitCount);
    const amplitude = (order === 0 ? 1 : 2) * Math.abs(sinc) * Math.hypot(real, imaginary) / halfBitCount;
    lines.push({frequency: Number((order / periodBits).toFixed(6)), amplitude});
  }
  return lines;
}

const comparisons = COMPARISONS.map(({keys, pattern}) => {
  const repeatedBits = pattern.repeat(128);
  const codes = lineCodes(repeatedBits, repeatedBits.length);
  const spectra = Object.fromEntries(keys.map(key => {
    const period = steadyPeriod(halfBitLevels(codes[key], key), pattern.length);
    return [key, {periodBits: period.length / 2, lines: harmonics(period)}];
  }));
  const peak = Math.max(...keys.flatMap(key => spectra[key].lines.map(line => line.amplitude)));
  for (const key of keys) {
    spectra[key].lines = spectra[key].lines.map(line => ({
      frequency: line.frequency,
      amplitude: Number((100 * line.amplitude / peak).toFixed(2)),
    }));
  }
  return {keys, pattern, spectra};
});

const output = fileURLToPath(new URL('../course/interactives/line-spectrum-data.js', import.meta.url));
writeFileSync(output, `// Generated by scripts/generate_line_spectra.mjs; do not edit by hand.\nexport const LINE_SPECTRA = ${JSON.stringify({maxFrequency: MAX_FREQUENCY, comparisons})};\n`);
console.log('Wrote Fourier lines for three periodic line-code comparisons.');
