project:
  type: website
  output-dir: _site
  resources:
    - interactives/*.js
    - interactives/audio-channel-coding/**
    - assets/audio-channel-coding/**
    - styles/companding-line.css
    - styles/scrambler.css

website:
  title: "ОПИСиС"
  description: "Новая версия курса"
  site-url: https://temasw.github.io/intro-to-networking/
  search: true
  page-navigation: true
  navbar:
    left:
      - text: "О курсе"
        href: index.qmd
      - text: "Лекции"
        href: lectures/index.qmd
      - text: "Практика"
        href: practice/index.qmd
      - text: "Лабораторные"
        href: labs/index.qmd
      - text: "Справочник"
        href: reference/index.qmd

format:
  html:
    lang: ru
    include-after-body: _includes/navigation.html
    theme:
      light: [cosmo, styles/base.scss]
      dark: [darkly, styles/base.scss]
    respect-user-color-scheme: true
    toc: true
    anchor-sections: true

execute:
  freeze: auto
